apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  template:
    spec:
      containers:
      - name: helloworld
        env:
        - name: JAVA_TOOL_OPTIONS
          value: >-
            -XX:MinRAMPercentage=40 -XX:MaxRAMPercentage=90
            -XX:MaxDirectMemorySize=10M
            -XX:MaxMetaspaceSize=96435K
            -XX:ReservedCodeCacheSize=240M
            -Xss1M
            -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8787
            -Djava.security.egd=file:/dev/./urandom
        - name: SPRING_CONFIG_LOCATION
          value: "classpath:/,file:/config/"
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        volumeMounts:
          - name: helloworld-config
            mountPath: "/config"
            readOnly: true
      volumes:
        - name: helloworld-config
          configMap:
            name: helloworld-config-map
            items:
              - key: "application-k8s.properties"
                path: "application-k8s.properties"