apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patchesStrategicMerge:
  - helloworld-service.yaml
  - helloworld-deployment.yaml
configMapGenerator:
  - name: helloworld-config-map
    files:
      - application-kubernetes.properties
namePrefix: dev-