apiVersion: v1
kind: LimitRange
metadata:
  name: helloworld-limit-range
spec:
  limits:
  - default:
      cpu: "1"
    defaultRequest:
      cpu: "0.5"
    max:
      cpu: "3"
    min:
      cpu: "0.1"
    type: Container
