apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - helloworld-service-account.yaml
  - helloworld-network-policy.yaml
  - helloworld-limit-range.yaml
  - helloworld-resource-quota.yaml
patchesStrategicMerge:
  - helloworld-deployment.yaml
configMapGenerator:
  - name: helloworld-config-map
    files:
      - application-kubernetes.properties
