apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app: helloworld
    version: 1.0.0
    app.kubernetes.io/name: helloworld
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/instance: helloworld-8d007602
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: helloworld
spec:
  ports:
    - name: http-service
      port: 8080
      protocol: TCP
    - name: http-actuator
      port: 8081
      protocol: TCP
    - name: http-debug
      port: 8787
      protocol: TCP
  selector:
    app.kubernetes.io/name: helloworld
    app.kubernetes.io/instance: helloworld-8d007602
